version: "3.8"
services:
  horde-dreamer:
    image: dynamedia/ai-horde-dreamer
    volumes:
        - ./workspace:/workspace
        # Will echo to root-owned authorized_keys file;
        # Avoids changing local file owner
        - ./authorized_keys:/root/.ssh/authorized_keys_mount
    environment:
        # Limit GPU count. Default uses all NVIDIA cards found
        #GPU_COUNT: 1
        
        # AI-Horde-Worker branch or commit hash
        HORDE_WORKER_BRANCH: "main"
        
        # Web UI auth credentials - Change the values.
        WEB_USER: "admin"
        WEB_PASSWORD: "password"
        
        # Set bridgeData.yaml variables
        # prefix any bridgeData.yaml key with BRIDGE_...
        BRIDGE_API_KEY: "0000000000"
        BRIDGE_WORKER_NAME: "Docker Dreamer"
        BRIDGE_MAX_THREADS: 1
        BRIDGE_MAX_POWER: 8
        BRIDGE_MODELS_TO_LOAD: "Top 2, stable_diffusion_inpainting"
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - 2222:22
        # Web UI
        - 7860:7860