version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        IMAGE_BASE: ${IMAGE_BASE}
      tags:
        - "ghcr.io/ai-dock/ai-horde-dreamer:${IMAGE_TAG}"
        
    image: ghcr.io/ai-dock/ai-horde-dreamer:${IMAGE_TAG}
    
    security_opt:
      # For Rclone mount
      - apparmor:unconfined
    
    cap_add:
      # For Rclone mount
      - SYS_ADMIN
    
    devices:
      # For Rclone mount
      - "/dev/fuse:/dev/fuse"

    volumes:
      # For Rclone mount
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./config/rclone:/etc/rclone
      # Workspace
      - ./workspace:${WORKSPACE}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning.sh:/opt/ai-dock/bin/provisioning.sh
    
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST}:${SSH_PORT}
        # redirect to Cloudflare quick tunnel
        - ${REDIRECTOR_PORT_HOST}:1111
        # Websocket log viewer
        - ${LOG_VIEWER_PORT_HOST}:1122
        # Rclone webserver for interactive configuration
        - ${RCLONE_PORT_HOST}:53682
        # AI Horde web UI
        - ${HORDE_WEBUI_PORT_HOST}:7860
        # Jupyter
        - ${JUPYTER_PORT_HOST}:${JUPYTER_PORT}
   
    environment:
        # AI-Horde-Worker branch or commit hash
        - HORDE_WORKER_BRANCH=${HORDE_WORKER_BRANCH}
        - HORDE_DEV=${HORDE_DEV}
        - HORDE_SKIP_SERVICE=${HORDE_SKIP_SERVICE}
        - GPU_COUNT=${GPU_COUNT}
        
        # Web UI auth credentials - Change the values.
        - WEB_USER=${WEB_USER}
        - WEB_PASSWORD=${WEB_PASSWORD}
        
        # Set bridgeData.yaml variables
        # prefix any bridgeData.yaml key with BRIDGE_...
        - BRIDGE_API_KEY=${BRIDGE_API_KEY}
        - BRIDGE_WORKER_NAME=${BRIDGE_WORKER_NAME}
        - BRIDGE_MAX_THREADS=${BRIDGE_MAX_THREADS}
        - BRIDGE_MAX_POWER=${BRIDGE_MAX_POWER}
        - BRIDGE_MODELS_TO_LOAD=${BRIDGE_MODELS_TO_LOAD}
        
        ### Base Variables ###
        # Allows running true SSH alongside provider proxy SSH
        - SSH_PORT=${SSH_PORT}
        - WORKSPACE=${WORKSPACE}
        - JUPYTER_PORT=${JUPYTER_PORT}
        - JUPYTER_TOKEN=${JUPYTER_TOKEN}
        - JUPYTER_MODE=${JUPYTER_MODE}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS}
        #- PROVISIONING_SCRIPT=https://raw.githubusercontent.com/ai-dock/base-image/main/demo/provisioning.sh
